import type {Metadata} from "next";
import localFont from "next/font/local";
// import { Inter } from "next/font/google";
import "./globals.css";
// import StoreProvider from "./StoreProvider";
import Navbar from "./components/nav"

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Stocker App",
    description: "Generated by create next app",
};

// const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html className="flex flex-col min-h-screen " >
        {/*<body className={inter.className}>*/}
        <body className="bg-sky-50 min-h-screen antialiased">
        {/*<StoreProvider>*/}
            <Navbar />
            {children}
        {/*</StoreProvider>*/}
        </body>
        </html>
        // <html lang="en">
        // <body
        //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // >
        // {children}
        // </body>
        // </html>
    );
}
